(* This file is automatically generated by configure. Do not manually edit. *)
let install_bin_dir = "/usr/local/bin" ;;
let install_lib_dir = "/usr/local/lib/focalize" ;;
let caml_byt_compiler = "ocamlc" ;;
let caml_bin_compiler = "ocamlopt" ;;
let coq_compiler = "coqc" ;;
let dedukti_compiler = "" ;;
let sukerujo_compiler = "" ;;
let zvtov_compiler = "/usr/local/bin/zvtov" ;;
let zenon_compiler = "zenon" ;;
let zenon_libdir = "/usr/local/lib/zenon" ;;
(* End of generated source file. *)
